[package]
name = "chip8-iced"
version = "0.1.0"
edition = "2024"

[dependencies]
chip8-core = {path = "../chip8-core"}
bytes = "1.10"
iced = {version = "0.13", features = ["tokio", "image-without-codecs"]}